on:
  workflow_call:
    inputs:
      REMOTE_URL:
        required: false
        type: string
        default: ${{ atomgit.repositoryurl }}
      pr_id:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.number }}
      IMAGE_FLAG:
        required: true
        type: string
        description: "Full SWR image URL, e.g. swr.<region>.<org>/mindx_arm:tag"
      TARGET_BRANCH:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.base.ref }}
      runs_on_arch:
        required: true
        type: string
        description: "x86 or arm"
      servicename:
        required: false
        type: string
        default: $(echo "${{ atomgit.repository }}" | cut -d '/' -f 2)
      DEFAULT_BRANCH:
        required: false
        type: string
        default: "master"

jobs:
  JOB_compile:
    name: JOB_compile
    select: selected_by_default
    runs-on: [ self-hosted, "${{ inputs.runs_on_arch }}", cpu=32 ]
    container:
      image: ${{ inputs.IMAGE_FLAG }}
      options: --user root
    steps:
      - name: clone repo and merge PR
        run: |
          set -x
          artifact_directory="${ATOMGIT_WORKSPACE}/artifacts"
          mkdir -p "${artifact_directory}"
          touch "${artifact_directory}/empty.run"

          apt install -y git git-lfs
          git lfs install
          git clone --no-tags --single-branch -b ${{ inputs.TARGET_BRANCH }} ${{ inputs.REMOTE_URL }} ${{ inputs.servicename }}
          cd ${{ inputs.servicename }}

          git fetch --no-tags origin refs/merge-requests/${{ inputs.pr_id }}/head:pr_${{ inputs.pr_id }}
          git reset --hard "origin/${{ inputs.TARGET_BRANCH }}"
          git checkout -b new_${{ inputs.TARGET_BRANCH }}
          git config --global user.name AtlasAccount
          git config --global user.email AtlasAccount@noreply.gitcode.com
          git merge --no-edit pr_${{ inputs.pr_id }}
          git lfs pull

          git diff-tree -r --name-only --no-commit-id origin/${{ inputs.TARGET_BRANCH }} HEAD > ${ATOMGIT_WORKSPACE}/change.txt
          cat ${ATOMGIT_WORKSPACE}/change.txt

          if [ "${{ inputs.TARGET_BRANCH }}" != "${{ inputs.DEFAULT_BRANCH }}" ]; then
              mkdir -p .gitcode/workflows
              git clone --no-tags --single-branch --depth 1 -b ${{ inputs.DEFAULT_BRANCH }} ${{ inputs.REMOTE_URL }} ${ATOMGIT_WORKSPACE}/tempdir
              cp -fr ${ATOMGIT_WORKSPACE}/tempdir/.gitcode/workflows/scripts .gitcode/workflows/ 2>/dev/null || true
              cp -fr ${ATOMGIT_WORKSPACE}/tempdir/.gitcode/workflows/config .gitcode/workflows/ 2>/dev/null || true
              rm -fr ${ATOMGIT_WORKSPACE}/tempdir
          fi

      - name: prepare_dependency
        run: |
          set -e
          echo "ATOMGIT_WORKSPACE=${ATOMGIT_WORKSPACE}"

          if [ ! -d "${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/opensource/" ]; then
              mkdir -p ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/opensource/
          fi
          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/
          git clone -b v2.5.0-h1 https://gitcode.com/cann-src-third-party/makeself.git makeself_patch
          git clone -b release-2.5.0 https://gitcode.com/gh_mirrors/ma/makeself.git

          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/opensource/

          git clone -b v2.13.6 https://gitcode.com/GitHub_Trending/py/pybind11.git ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/acc_data/3rdparty/pybind/pybind11
          git clone -b release-1.11.0 https://gitcode.com/GitHub_Trending/go/googletest.git ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/acc_data/3rdparty/gtest/googletest

      - name: compile
        run: |
          set -ex
          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/opensource.tar.gz
          # obsutil cp obs://mindcluster/opensource.tar.gz ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/opensource.tar.gz
          export PATH=$PATH:/opt/buildtools/python-3.11.4/bin/
          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/build_script
          export GTEST_HOME=/usr/local/googletest
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/test/data/videos/video_1min_30fps.avi
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/test/data/videos/test_acc.mp4
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/test/data/videos/video_1min_30fps.mp4
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/test/data/videos/video_200width.mp4
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/test/image/assets/dog_1920_1080.jpg
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/test/image/assets/dog_1920_1080.png
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/MultimodalSDK/test/assets/dog_1920_1080.jpg
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/MultimodalSDK/test/assets/dog_1920_1080.png
          chown -R 0:0 ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/MultimodalSDK/test/assets/test_aac.mp4
          ls -la ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/AccSDK/acc_data/3rdparty/gtest/googletest/googletest
          bash build_merge.sh test
