# Dev Container image for MultimodalSDK source development.
# Build: docker build --network host -t multimodalsdk-dev:ubuntu22.04 .devcontainer/

FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/multimodalsdk:26.1.0-cann9.1.0-torch_npu2.6.0.post5-910b-ubuntu22.04-py3.12-aarch64

ENV Python3_EXECUTABLE=/usr/local/python3.12.13/bin/python3

WORKDIR /workspace/MultimodalSDK
